name: Build and Lint

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx nx run-many -t lint
      - name: Build
        run: npx nx run-many -t build